# it works?
language: node_js
node_js:
    - node
cache:
    directories:
        - node_modules
env:
    - REACT_APP_STAGE=development
    - REACT_APP_STAGE=production
script:
    - npm run build
deploy:
    - provider: script
      script: ./deploy.sh
      on:
          branch: master
          condition: $REACT_APP_STAGE = development
    - provider: script
      script: ./deploy.sh
      env:
          - JARDA_VAR=hellofrance
      on:
          branch: production
          condition: $REACT_APP_STAGE = production
