# it works?
language: node_js
node_js:
    - node
cache:
    directories:
        - node_modules
env:
    - secure: "K0kuX+bpurVNWPxU0gLY3dIhbpy2Vw8pDZTJtZ+vKa/Jfvz8HCXXgzkT0N1HYB2WNE9iXEUdIlAHh5IA6/d7Gm1YUlE9EJaVNF7KseEgqKTgYcSJ4QTs4gaMCEc8N08LN++PvVj+ras6sVPX+qxt0lhLC8c9M964zy7UA7cuoTc0JWiXXfEECxSMYWd2SKWp/Kf+ZIKPrYCfCQVDDBkJQasNcwSgVEDGi9+eGV4Of8PckVmabCRoHIY+UU6xytCb2nzaEaoDMHBVpIr6dWOlL6ZjvLDd3o1D7KB3EYumCsv3fRhM2U+neL8Jm0wXglcg1h3/sz27PdHK6AFbvTTRVjetf+wuaFtJgAmpgjKdtF1jspG4+KMxY/uCkmIEYEqes/AkwaIfGK5ANDUhHWK1AMgYS4N8td/979e3tc8NxhrApXmnLW3BjDCV8sD4g21lWj/vzhZF6yQYd7wK0NaJvQ4p0Lts5jiyXFQ/WGr8+xBf5bl05h8aHAdFCXlHqxy8nQ3BvodN+QuK+RE7Nfxh7xSuZxx7/0/4ZVrvnqht/jX5rewej4gf1ofUPbV9aa4PqGXfXQ1WlG0LtchxAxRw8a2oAEbFNuC8NhH5SrXFxxctqKI1Et02lUiJNKwY2ruA6fgYi7q6/Fs9H+iHabh7oNI4HkhrY3X1aTuYVRKnbCY="
    - secure: "q3CegChcmbwpPUpSe/8kFY7GMciJQaeMbG4JTJGrECXEL4RkEYhidbXPJ50Z3JS07riO8RzZE9Ocvsmeexri7JYoIKJpVfKTHjd33FhyLJptDQWCnl3EiIkPuJfswjCIMZtFdl/HPr6OsMSz/5gQFYI+KRZeD+43PAA74NStm0dtLKLwnOBgMJEPKOlmB0Mqj3eYqJVllsDWH6GH9lQZkFeMk9GBuEqk4cCHMOIkT9PVn4TLwwNcEGKQnSv6Envqr0QZFIJm1gvG704wkztX9S9B2Zy2aRaJQ/OQ7QAXhFTswohup+30+gVMs71DMbD4lHSwYP4In7EYTjkoLy9S4RBpZshUxQpSyBgVWExbbTdrYud8Ag+gg0i8KOaSDviiJiNN4ntqHtrJjUtY9PXIuVbO9oUp00AQYsNZ6NIbF5l7VJNsOSW36wUAERvwTfSCoLMW3B5Zwm7BUUiC/Wd8I+A1O/uJus46UN7RoKx1M2WmwyU3Q49M/DYBRKMG4vxVFVUzKzz9UWN0cLuzE6xrHTCk/x50CIxxhFt73mLoD3CvUxGDFbC0SZKj7o4oeyYFhSXwTeY5Mznh+epOUro0BBbRe9Oh69oshxB9VjH59QfV5ywOOe8npnDgbyNRG8h1gdLIR8aWa2Vuc7I5fGbMSMCCHOuW5ssB9BdxEnUxULM="
script:
    - npm run build
deploy:
    - provider: script
      script: ./deploy.sh
      on:
          branch: master
          condition: $REACT_APP_STAGE = development
    - provider: script
      script: ./deploy.sh
      env:
          - JARDA_VAR=hellofrance
      on:
          branch: production
          condition: $REACT_APP_STAGE = production
