language: node_js
node_js:
    - node
cache:
    directories:
        - node_modules
script:
    - npm run build
deploy:
    - provider: script
      script: ./deploy.sh
      env: JARDA_VAR=hello-master
      on:
          branch: master
    - provider: script
      script: ./deploy.sh
      env: JARDA_VAR=hello_france
      on:
          branch: le_branch
